kind: Service
apiVersion: v1
metadata:
  name: iso-bridge-service
  namespace: camel-bridge
spec:
  type: LoadBalancer
  selector:
    app: iso-bridge
  ports:
  # Default port used by the image
  - name: netty-tcp
    port: 9200
    protocol: TCP
    targetPort: 9200

# ## IGNORED - for testing purpose
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: iso-bridge-service-nodeport
#   namespace: camel-bridge
# spec:
#   type: NodePort
#   selector:
#     app: iso-bridge
#   ports:
#   # Default port used by the image
#   - name: netty-tcp
#     nodePort: 32000
#     protocol: TCP
#     port: 9200

